### ISSUE TITLE
more customizing the text, please

### ISSUE THREAD

**Issue by Breadcrochets** [naeruru/mimiuchi#20]
Specifically, I would appreciate it if your service offered a dyslexia friendly font, thank you! <3
https://opendyslexic.org/ this one works great for me, i used it on web captioner (which will shut down at the end of october), and it's open source and free to use

**Comment by naeruru** [comment]
would be happy to add more fonts and that one as well. will try to do this asap^^

I did not know web captioner was shutting down. that's sad. well, once I get through some thesis work, I will be focusing on this application with many new features. feel free to suggest new features

**Comment by naeruru** [comment]
awh thank you!! (っ ॑꒳ ॑c) 

I can prioritize those too. by hanging on to the subtitles, do you mean how they fade away? there is an option in the appearance settings to adjust how long they stay there. you can even uncheck the box next to it and they will never disappear. not sure if this is what you are referring to

- ✅ button disables text disappearing feature 
- fade text after 〇〇 seconds textfield changes how long till it will fade away
- fade text for 〇〇 seconds textfield changes how long the text fades out for

**Comment by Breadcrochets** [comment]
ah i see that now, thanks. I would appreciate the option to add a line break instead of fading out when i don't talk for xx seconds

**Comment by naeruru** [comment]
### [feature request 1] video of font selection. I want to improve the UI but for now it will just be simple like this

![font_selection](https://github.com/naeruru/mimiuchi/assets/9059594/d9b68726-7cd5-4cc6-947e-2a5c746dae95)

###  [feature request 2] transcript downloads
transcripts will look like this:
```
[2023-09-17T04:23:55.264Z] hello my name is nae
[2023-09-17T04:28:29.036Z] こんにちは！
```
![image](https://github.com/naeruru/mimiuchi/assets/9059594/ffb920b0-f0f8-4b54-bd06-fc4ab703abc6)

### [feature request 3] line breaks
in progress. will take a little bit of time to do. when i finish this I will push it to mimiuchi.com and then work on the ui more later

**Comment by Breadcrochets** [comment]
This is awesome, thanks for listening to my concerns. Can't wait til it gets updated!

**Comment by naeruru** [comment]
I finished all the features^^ pushing to [mimiuchi.com](https://mimiuchi.com/) and will then I will close the issue. if you want a similar experience to webcaptioner, use these options in the [appearance](https://mimiuchi.com/settings/appearance) page 


![image](https://github.com/naeruru/mimiuchi/assets/9059594/df2a551f-f232-4234-8599-6fdc9b791195)
