### ISSUE TITLE
[Bug?] speech text is not visible

### ISSUE THREAD

**Issue by Fripplo** [naeruru/mimiuchi#27]
I'm using Microsoft Edge since that browser have support for Web Speech API, however.. a few months ago it stopped working for some reason? I haven't done any type of change on the browser like settings or anything. What may be the problem for the text also not showing up like I'm showing on the 1st image?
![hm1](https://github.com/naeruru/mimiuchi/assets/25721823/56f9e55d-35e7-4b6a-b53d-190cb2ea4690)
![hm2](https://github.com/naeruru/mimiuchi/assets/25721823/d7b9654c-d650-4d34-98af-a89056140385)

**Comment by Fripplo** [comment]
**Opss sorry... I accidentally closed the issue.. I'm not used to github** >_<

Anyways, the issue seemed to be fixed by going into Settings->Translation and enabling "Show original phrase before translating" even if the option for translation is not enabled. Showed on this image 
![hmm3](https://github.com/naeruru/mimiuchi/assets/25721823/dfcb0d91-ef75-4510-8266-2eead3bb4721)

**Comment by naeruru** [comment]
Oh you're right. I will fix this ASAP after the other two pull requests.

**Comment by naeruru** [comment]
fixed with d4123615d235bfb8726e540b369c5eb4e7c1ef60. I will close this issue when I push it to mimiuchi.com ^^

**Comment by Fripplo** [comment]
Great! :3
