### ISSUE TITLE
Add support for real-time text in "Type a message"

### ISSUE THREAD

**Issue by mdrejhon** [naeruru/mimiuchi#40]
Hello!

I'm a deaf software developer, who uses both transcription (for incoming text) and keyboard (for outgoing text).  

I've been immensely enjoying the ability to use mimiuchi as a free alternative to Otter or other paid services which I also use.   I like the fact that mimiuchi supports WebHook and WebSockets.  

Thanks to "Type a message", mimiuchi conveniently can be programmed as a browser-based keyboard for another device (with a bit of programming glue).  I also like using mimiuchi to turn a phone/iPad into a portable keyboard for a big screen.   

### Use case: Mimiuchi acts as a substitute for a bluetooth keyboard

Allows guests to bring their own device, to use as a keyboard for a main communications screen.  When no spare keyboard is available.

Or that we're doing chatting on-the-go across the table (like a Ubiduo assistive device) privately between two offline devices (mimiuchi works offline once cached).  Or multiple chatters (one at a time) chatting in real time to a central big screen (e.g. living room TV or conference room projector) in front of them.

Basically any iPhone/Android/iPad/laptop/etc can become a portable guest keyboard for another device such as a main big chat screen (on TV).  Transcriptions still work but some people prefer to type.   The guest typist sitting next to me, can use their device to send messages to the big screen (through mimiuchi) which works instead of a Bluetooth keyboard.

However, it's not as realtime-feeling as a bluetooth keyboard typing to a laptop connected directly to a big screen. It's nice giving people a choice to speak or type...

So as a workaround for this use case:

Is it possible to add a realtime mode to the "Type a Message" where keypresses are sent one by one in real time?   Or even as batches every 0.25 second or 0.5 seconds?  (A configurable time-based buffer to rate-limit webhook/websocket requests).

Basically an optional "Real time typing" mode where keypresses are sent individually (or almost).

**Comment by mdrejhon** [comment]
Some UX thoughts:

- A Setting that enables real time text mode (Default off)
- Keep the UI unchanged, except that differentials are transmitted (updates to Type a Message textbox is monitored on a timer).  Type a Message cleared upon Enter.  
- Modify the UI to type directly into the main text area.
- Other idea

Whichever is easier to adapt mimiuchi architecture to double as a realtime keyboard-typing client.

**Comment by naeruru** [comment]
Sure, I can work on this! I had some ideas for a separate, typing focused home screen, and I’ll mess with that more this week and next. I like your simple idea of just making the text window a text area of some sort

**Comment by mdrejhon** [comment]
Fantastic.  When will this version be put up at www.mimiuchi.com?   I'll give it a test.

**Comment by naeruru** [comment]
I just pushed it live now! Sorry for the wait. Yeah I think it is a good change. However, the documentation is a little sparse on these features and I'd like to focus on that next so people can understand the endpoints a little better. Also the UI on a smartphone for typing could be a little better. The current larger footer option is simply a stopgap at the moment. I'll work on it more soon

**Comment by mdrejhon** [comment]
Understood!  mimiuchi is a great accessibility app for people who used WebCaptioner in the past...

But your app has other goodies that makes it double as a great "guest keyboard" app that has 3 modes (line input typing, realtime typing, and dictation).  

I'd love you to (better) emphasize your app ability to be used as a guest keyboard.  

Related feature suggestion (brainstorm): In theory you can have QR codes on the central chat screen that opens up mimiuchi to a specific IP address. The user can then broadcast their communications back to the central screen (splitscreen, IRC screen, groupchat text style, etc).  Don't know what the security implications are (analysis needed, good thought needed) but the ability to specify the REST/websocket as part of a URL argument would work; at least when mimiuchi is used in a localhost situation.
