### ISSUE TITLE
Feature Request: Outlined text or drop shadow to increase contrast when keying out background.

### ISSUE THREAD

**Issue by domesticatedviking** [naeruru/mimiuchi#44]
Hey - thank you for this awesome project.   I'm using it with OBS studio to subtitle live events.  
I'm already able to use a chroma key filter to make the background transparent, however it would be very helpful if there was an option for text to be rendered with a glow/outline/drop shadow in a contrasting color so that it will be readable no matter what image it is being displayed on top of.

Many thanks!!  Great work!!

**Comment by naeruru** [comment]
sure! I just put together a working version of this feature. In the settings there is an option for outline size and color! see video for example.

https://github.com/user-attachments/assets/653446d9-4f90-43bf-bbd3-e5df057048b6

**Comment by domesticatedviking** [comment]
Oh wow!  Really impressed that you added this already!  Thank you very much!!!
